// <auto-generated />
using System;
using Literature.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace literature.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20190422122209_Orders")]
    partial class Orders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Literature.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("OrderDate");

                    b.Property<bool>("OrderDelivered");

                    b.Property<bool>("OrderPlaced");

                    b.Property<int?>("PublisherID");

                    b.HasKey("ID");

                    b.HasIndex("PublisherID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Literature.Models.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrderID");

                    b.Property<int?>("PublicationID");

                    b.Property<int>("Quantity");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("PublicationID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Literature.Models.Publication", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Language");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Publication");
                });

            modelBuilder.Entity("Literature.Models.Publisher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Literature.Models.Order", b =>
                {
                    b.HasOne("Literature.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherID");
                });

            modelBuilder.Entity("Literature.Models.OrderItem", b =>
                {
                    b.HasOne("Literature.Models.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID");

                    b.HasOne("Literature.Models.Publication", "Publication")
                        .WithMany()
                        .HasForeignKey("PublicationID");
                });
#pragma warning restore 612, 618
        }
    }
}
